import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'en' | 'uk';

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    'nav.games': 'Games',
    'nav.tournaments': 'Tournaments',
    'nav.leaderboard': 'Leaderboard',
    'nav.pricing': 'Pricing',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.start': 'Start',
    'nav.language': 'Language',
    'game.rooms': 'Game rooms',
    'game.create': 'Create New Game',
    'game.allScenarios': 'All scenarios',
    'game.join': 'Join',
    'game.lobby': 'Lobby',
    'game.players': 'players',
    'game.lobbyHostHint': 'Add club players manually, mark readiness, then start the match.',
    'game.lobbyPlayerHint': 'Wait for the host to start the table.',
    'game.tableSetup': 'Table setup',
    'game.tableSetupHint': 'Type the player name exactly as you want it to appear in the game. You can remove or mark players ready before starting.',
    'game.playerNamePlaceholder': 'Player name, e.g. Marta',
    'game.addPlayer': 'Add player',
    'game.ready': 'Ready',
    'game.waiting': 'Waiting',
    'game.toggleReady': 'Toggle ready',
    'game.emptyPlayers': 'No players yet. Add participants manually or share the room with players.',
    'game.startGame': 'Start Game',
    'game.playerPhaseHint': 'Play your role and follow the phase instructions.',
    'game.phase': 'Phase',
    'game.simulateNight': 'Simulate Night',
    'game.yourRole': 'Your role',
    'game.hostMode': 'Host mode',
    'game.runTable': 'Run the table',
    'game.alive': 'Alive',
    'game.mafia': 'Mafia',
    'game.citizens': 'Citizens',
    'game.events': 'Events',
    'game.startDay': 'Start Day',
    'game.startNight': 'Start Night',
    'game.citizensWin': 'Citizens win',
    'game.mafiaWin': 'Mafia win',
    'game.recordEvent': 'Record an event',
    'game.recordEventHint': 'Use this as the host journal: votes, checks, saves, eliminations, or any table note.',
    'game.type': 'Type',
    'game.note': 'Note',
    'game.notePlaceholder': 'Example: Sheriff checked Marta, not Mafia',
    'game.record': 'Record',
    'game.privateNotes': 'Private organizer notes',
    'game.privateNotesPlaceholder': 'Strategy notes, fouls, disputed moments, reminders',
    'game.role': 'Role',
    'game.hidden': 'Hidden',
    'game.markEliminated': 'Mark eliminated',
    'game.revive': 'Revive',
    'game.vote': 'Vote',
    'game.matchLog': 'Match log',
    'game.newestFirst': 'Newest first',
    'game.noEvents': 'No events yet. Add the first note above when something important happens.',
    'game.completed': 'Game completed',
    'game.resultSaved': 'Result saved to the match log. You can still review players and events.',
    'game.name': 'Game name',
    'game.scenario': 'Scenario',
    'hint.openRoom': 'Open a room to manage the table.',
    'hint.completed': 'Game is complete. Review the log or start a new room for the next table.',
    'hint.addPlayers': 'Add players in the lobby before starting the match.',
    'hint.assignRoles': 'Assign roles to every player before serious phase tracking.',
    'hint.night': 'Night phase: record Mafia, Doctor, and Sheriff actions as they happen.',
    'hint.day': 'Day phase: track votes, eliminations, and important discussion notes.',
    'landing.badge': 'Premium online social deduction',
    'landing.heroTitle': 'Play Mafia. Online. Together.',
    'landing.for': 'For',
    'landing.word.players': 'Players',
    'landing.word.clubs': 'Clubs',
    'landing.word.champions': 'Champions',
    'landing.startPlaying': 'Start Playing',
    'landing.forClubs': 'For Clubs',
    'landing.featuresTitle': 'Everything you need to run the perfect game',
    'landing.feature.automation.title': 'Result Automation',
    'landing.feature.automation.text': 'Auto role assignment, phase transitions, voting outcomes, and result recording keep the table focused on deduction.',
    'landing.feature.scenarios.title': 'Scenario Support',
    'landing.feature.scenarios.text': 'Classic, Advanced, and Mini tables with clear role breakdowns.',
    'landing.feature.tournaments.title': 'Tournament Management',
    'landing.feature.tournaments.text': 'Registration, brackets, rounds, and prize tracking for club hosts.',
    'landing.feature.stats.title': 'Long-term Statistics',
    'landing.feature.stats.text': 'Win rates, role performance, ratings, achievements, and leaderboards that make progress feel real.',
    'landing.feature.cabinets.title': 'Player Cabinets',
    'landing.feature.cabinets.text': 'Personal profiles with game history and achievement badges.',
    'landing.howTitle': 'How it works',
    'landing.step.account': 'Create an account',
    'landing.step.game': 'Start or join a game session',
    'landing.step.victory': 'Play Day/Night phases to victory',
    'landing.pricingTitle': 'Plans for every table',
    'landing.free': 'Free',
    'landing.perMonth': 'per month',
    'landing.trial': 'Start Free Trial',
    'landing.leaderboardTitle': 'Leaderboard preview',
    'landing.review.nazar.text': 'The first online Mafia tool that feels built for serious tables.',
    'landing.review.iryna.text': 'Tournament nights are calmer now. Registration and results just work.',
    'landing.review.marko.text': 'The statistics made role practice addictive in the best way.',
    'landing.role.player': 'Player',
    'landing.role.organizer': 'Organizer',
    'landing.role.champion': 'Champion',
    'landing.ctaTitle': 'Ready to find the Mafia?',
    'landing.ctaButton': 'Enter the table',
    'plan.feature.5games': '5 games/month',
    'plan.feature.basicStats': 'Basic stats',
    'plan.feature.unlimitedGames': 'Unlimited games',
    'plan.feature.fullStats': 'Full stats',
    'plan.feature.leaderboard': 'Leaderboard',
    'plan.feature.tournaments': 'Tournaments',
    'plan.feature.prioritySupport': 'Priority support',
    'plan.feature.advancedHistory': 'Advanced history',
    'plan.feature.upTo50': 'Up to 50 players',
    'plan.feature.clubAnalytics': 'Club analytics',
    'plan.feature.unlimitedTournaments': 'Unlimited tournaments',
    'plan.feature.whiteLabel': 'White-label',
    'plan.feature.apiAccess': 'API access'
  },
  uk: {
    'nav.games': 'Ігри',
    'nav.tournaments': 'Турніри',
    'nav.leaderboard': 'Рейтинг',
    'nav.pricing': 'Тарифи',
    'nav.dashboard': 'Кабінет',
    'nav.logout': 'Вийти',
    'nav.login': 'Увійти',
    'nav.start': 'Почати',
    'nav.language': 'Мова',
    'game.rooms': 'Ігрові кімнати',
    'game.create': 'Створити гру',
    'game.allScenarios': 'Усі сценарії',
    'game.join': 'Приєднатись',
    'game.lobby': 'Лобі',
    'game.players': 'гравців',
    'game.lobbyHostHint': 'Додайте гравців клубу вручну, позначте готовність і запускайте гру.',
    'game.lobbyPlayerHint': 'Очікуйте, поки ведучий запустить стіл.',
    'game.tableSetup': 'Налаштування столу',
    'game.tableSetupHint': 'Введіть імʼя гравця так, як воно має відображатися у грі. До старту можна видаляти гравців або змінювати готовність.',
    'game.playerNamePlaceholder': 'Імʼя гравця, наприклад Марта',
    'game.addPlayer': 'Додати гравця',
    'game.ready': 'Готовий',
    'game.waiting': 'Очікує',
    'game.toggleReady': 'Змінити готовність',
    'game.emptyPlayers': 'Гравців ще немає. Додайте учасників вручну або поділіться кімнатою.',
    'game.startGame': 'Почати гру',
    'game.playerPhaseHint': 'Грайте свою роль і стежте за інструкціями фази.',
    'game.phase': 'Фаза',
    'game.simulateNight': 'Симулювати ніч',
    'game.yourRole': 'Ваша роль',
    'game.hostMode': 'Режим ведучого',
    'game.runTable': 'Керування столом',
    'game.alive': 'Живі',
    'game.mafia': 'Мафія',
    'game.citizens': 'Мирні',
    'game.events': 'Події',
    'game.startDay': 'Почати день',
    'game.startNight': 'Почати ніч',
    'game.citizensWin': 'Перемога мирних',
    'game.mafiaWin': 'Перемога мафії',
    'game.recordEvent': 'Записати подію',
    'game.recordEventHint': 'Використовуйте це як журнал ведучого: голосування, перевірки, лікування, вибування або нотатки столу.',
    'game.type': 'Тип',
    'game.note': 'Нотатка',
    'game.notePlaceholder': 'Приклад: Шериф перевірив Марту, не мафія',
    'game.record': 'Записати',
    'game.privateNotes': 'Приватні нотатки ведучого',
    'game.privateNotesPlaceholder': 'Стратегія, фоли, спірні моменти, нагадування',
    'game.role': 'Роль',
    'game.hidden': 'Приховано',
    'game.markEliminated': 'Позначити вибулим',
    'game.revive': 'Повернути',
    'game.vote': 'Голос',
    'game.matchLog': 'Журнал гри',
    'game.newestFirst': 'Нові зверху',
    'game.noEvents': 'Подій ще немає. Додайте першу нотатку вище, коли станеться щось важливе.',
    'game.completed': 'Гру завершено',
    'game.resultSaved': 'Результат збережено в журналі. Ви все ще можете переглянути гравців і події.',
    'game.name': 'Назва гри',
    'game.scenario': 'Сценарій',
    'hint.openRoom': 'Відкрийте кімнату, щоб керувати столом.',
    'hint.completed': 'Гру завершено. Перегляньте журнал або створіть нову кімнату для наступного столу.',
    'hint.addPlayers': 'Додайте гравців у лобі перед стартом гри.',
    'hint.assignRoles': 'Призначте ролі всім гравцям перед веденням фаз і статистики.',
    'hint.night': 'Нічна фаза: записуйте дії мафії, лікаря та шерифа.',
    'hint.day': 'Денна фаза: фіксуйте голосування, вибування та важливі нотатки обговорення.',
    'landing.badge': 'Преміальна онлайн-платформа для соціальної дедукції',
    'landing.heroTitle': 'Грайте в Мафію. Онлайн. Разом.',
    'landing.for': 'Для',
    'landing.word.players': 'гравців',
    'landing.word.clubs': 'клубів',
    'landing.word.champions': 'чемпіонів',
    'landing.startPlaying': 'Почати гру',
    'landing.forClubs': 'Для клубів',
    'landing.featuresTitle': 'Усе, що потрібно для ідеальної гри',
    'landing.feature.automation.title': 'Автоматизація результатів',
    'landing.feature.automation.text': 'Автоматичний розподіл ролей, зміна фаз, голосування та запис результатів допомагають зосередитись на дедукції.',
    'landing.feature.scenarios.title': 'Підтримка сценаріїв',
    'landing.feature.scenarios.text': 'Classic, Advanced і Mini столи з прозорими конфігураціями ролей.',
    'landing.feature.tournaments.title': 'Керування турнірами',
    'landing.feature.tournaments.text': 'Реєстрація, сітки, раунди й призи для клубних організаторів.',
    'landing.feature.stats.title': 'Довгострокова статистика',
    'landing.feature.stats.text': 'Відсоток перемог, ефективність ролей, рейтинг, досягнення та лідерборди, які роблять прогрес відчутним.',
    'landing.feature.cabinets.title': 'Кабінети гравців',
    'landing.feature.cabinets.text': 'Особисті профілі з історією ігор і бейджами досягнень.',
    'landing.howTitle': 'Як це працює',
    'landing.step.account': 'Створіть акаунт',
    'landing.step.game': 'Запустіть або приєднайтесь до ігрової сесії',
    'landing.step.victory': 'Проходьте фази дня й ночі до перемоги',
    'landing.pricingTitle': 'Тарифи для кожного столу',
    'landing.free': 'Безкоштовно',
    'landing.perMonth': 'на місяць',
    'landing.trial': 'Почати пробний період',
    'landing.leaderboardTitle': 'Превʼю рейтингу',
    'landing.review.nazar.text': 'Перший онлайн-інструмент для Мафії, який відчувається створеним для серйозних столів.',
    'landing.review.iryna.text': 'Турнірні вечори стали спокійнішими. Реєстрація і результати просто працюють.',
    'landing.review.marko.text': 'Статистика зробила тренування ролей по-справжньому захопливим.',
    'landing.role.player': 'Гравець',
    'landing.role.organizer': 'Організатор',
    'landing.role.champion': 'Чемпіон',
    'landing.ctaTitle': 'Готові знайти мафію?',
    'landing.ctaButton': 'Сісти за стіл',
    'plan.feature.5games': '5 ігор/місяць',
    'plan.feature.basicStats': 'Базова статистика',
    'plan.feature.unlimitedGames': 'Необмежені ігри',
    'plan.feature.fullStats': 'Повна статистика',
    'plan.feature.leaderboard': 'Рейтинг',
    'plan.feature.tournaments': 'Турніри',
    'plan.feature.prioritySupport': 'Пріоритетна підтримка',
    'plan.feature.advancedHistory': 'Розширена історія',
    'plan.feature.upTo50': 'До 50 гравців',
    'plan.feature.clubAnalytics': 'Клубна аналітика',
    'plan.feature.unlimitedTournaments': 'Необмежені турніри',
    'plan.feature.whiteLabel': 'White-label',
    'plan.feature.apiAccess': 'API-доступ'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<AppLanguage>((localStorage.getItem('mafia_language') as AppLanguage) || 'en');

  setLanguage(language: AppLanguage): void {
    this.language.set(language);
    localStorage.setItem('mafia_language', language);
    document.documentElement.lang = language === 'uk' ? 'uk' : 'en';
  }

  toggle(): void {
    this.setLanguage(this.language() === 'en' ? 'uk' : 'en');
  }

  t(key: string): string {
    return translations[this.language()][key] ?? translations.en[key] ?? key;
  }
}
